export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SOCIAL_AUTH_SUCCESS = "SOCIAL_AUTH_SUCCESS";
export const SOCIAL_AUTH_REQUEST = "SOCIAL_AUTH_REQUEST";
export const SOCIAL_AUTH_FAILURE = "SOCIAL_AUTH_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const EMAIL_VERIFY_FAILURE = "EMAIL_VERIFY_FAILURE";
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS";
export const EMAIL_VERIFY_REQUEST = "EMAIL_VERIFY_REQUEST";

export const RESET_FAILURE = "RESET_FAILURE";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_REQUEST = "RESET_REQUEST";

export const PWD_UPDATE_REQUEST = "PWD_UPDATE_REQUEST";
export const PWD_UPDATE_SUCCESS = "PWD_UPDATE_SUCCESS";
export const PWD_UPDATE_FAILURE = "PWD_UPDATE_FAILURE";
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILURE = "GET_ARTICLE_FAILURE";

export const CREATE_ARTICLE_REQUEST = "CREATE_ARTICLE_REQUEST";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";

export const BOOKMARK_ARTICLE_REQUEST = "BOOKMARK_ARTICLE_REQUEST"
export const BOOKMARK_ARTICLE_SUCCESS = "BOOKMARK_ARTICLE_SUCCESS"
export const BOOKMARK_ARTICLE_FAILURE = "BOOKMARK_ARTICLE_FAILURE"

export const UN_BOOKMARK_ARTICLE_REQUEST = "UN_BOOKMARK_ARTICLE_REQUEST"
export const UN_BOOKMARK_ARTICLE_SUCCESS = "UN_BOOKMARK_ARTICLE_SUCCESS"
export const UN_BOOKMARK_ARTICLE_FAILURE = "UN_BOOKMARK_ARTICLE_FAILURE"

export const GET_BOOKMARKED_SUCCESS = "GET_BOOKMARKED_SUCCESS"
export const GET_BOOKMARKED_FAILURE = "GET_BOOKMARKED_FAILURE"
export const GET_BOOKMARKED_REQUEST = "GET_BOOKMARKED_REQUEST"

export const POST_RATING_REQUEST = "POST_RATING_REQUEST";
export const POST_RATING_SUCCESS = "POST_RATING_SUCCESS";
export const POST_RATING_FAILURE = "POST_RATING_FAILURE";

export const GET_RATING_REQUEST = "GET_RATING_REQUEST";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_FAILURE = "GET_RATING_FAILURE";


export const LIKE_ARTICLE_REQUEST = "LIKE_ARTICLE_REQUEST";
export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTILE_FAILURE = "LIKE_ARTICLE_FAILURE";

export const DISLIKE_ARTICLE_REQUEST = "DISLIKE_ARTICLE_REQUEST";
export const DISLIKE_ARTICLE_SUCCESS = "DISLIKE_ARTICLE_SUCCESS";
export const DISLIKE_ARTILE_FAILURE = "DISLIKE_ARTICLE_FAILURE";

export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";

export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAILURE = "UNFOLLOW_FAILURE";
export const SUBSCRIBE_REQUEST = "SUBSCRIBE_REQUEST";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAILURE = "SUBSCRIBE_FAILURE";

export const UNSUBSCRIBE_REQUEST = "UNSUBSCRIBE_REQUEST";
export const UNSUBSCRIBE_SUCCESS = "UNSUBSCRIBE_SUCCESS";
export const UNSUBSCRIBE_FAILURE = "UNSUBSCRIBE_FAILURE";



export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";

export const GET_SINGLE_NOTIFICATION_REQUEST = "GET_SINGLE_NOTIFICATION_REQUEST";
export const GET_SINGLE_NOTIFICATION_FAILURE = "GET_SINGLE_NOTIFICATION_FAILURE";
