export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';
export const SOCIAL_AUTH_REQUEST = 'SOCIAL_AUTH_REQUEST';
export const SOCIAL_AUTH_FAILURE = 'SOCIAL_AUTH_FAILURE';


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const EMAIL_VERIFY_FAILURE = "EMAIL_VERIFY_FAILURE"
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS"
export const EMAIL_VERIFY_REQUEST = "EMAIL_VERIFY_REQUEST"